/Dashboards/Office 365.json:
- bs-discover
- dikobraz
- kibana-sample
- AliveChicken78
/Dashboards/Refactored dasbhoard.json:
- bs-discover
- bs-speed
- kibana-sample
/import_test.json:
- test 2
- test 1
- default
/test.html:
- test 2
- default
/test.json: '*'
/test_library_03:
- default
