stages:
  - deploy

deploy staging:
  stage: deploy
  tags:
    - docker
  image: 
    name: squidfunk/mkdocs-material
    entrypoint: [""]
  script:
    - apk update && apk add openssh-client rsync
    - pip3 install mkdocs-print-site-plugin mkdocs-awesome-pages-plugin mkdocs-glightbox mkdocstrings mkdocstrings[python] mkdocs-git-revision-date-localized-plugin
    - mkdir -p ~/.ssh
    - echo "$DEPLOY_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - mkdir /output
    - mkdocs build --site-dir /output
    # For other languages
    # - (cd ./cs && mkdocs build --site-dir /output/cs)
    - rsync -r -a -v -e ssh --delete /output/ "$RSYNC_USER"@"$TARGET_SERVER":"$STAGING_DIR"
  only:
    - master

deploy production:
  stage: deploy
  tags:
    - docker
  image: 
    name: squidfunk/mkdocs-material
    entrypoint: [""]
  script:
    - apk update && apk add openssh-client rsync
    - pip3 install mkdocs-print-site-plugin mkdocs-awesome-pages-plugin mkdocs-glightbox mkdocstrings mkdocstrings[python] mkdocs-git-revision-date-localized-plugin
    - mkdir -p ~/.ssh
    - echo "$DEPLOY_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - mkdir /output
    - mkdocs build --site-dir /output
    # For other languages
    # - (cd ./cs && mkdocs build --site-dir /output/cs)
    - rsync -r -a -v -e ssh --delete /output/ "$RSYNC_USER"@"$TARGET_SERVER":"$PRODUCTION_DIR"
  only:
    - production
