site_name: ASAB

theme:
  name: "material"
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate #
    - navigation.tabs
    - navigation.footer
    - navigation.indexes
    - attr_list
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - def_list
    - navigation.tracking

  icon:
    admonition:
      # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#fontawesome
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

  font:
    text: Verdana

  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: yellow
      toggle:
        icon: material/brightness-4
        name: Switch to light mode



plugins:
  - mkdocstrings:
      markdown_extensions:
        - pymdownx.superfences:
            custom_fences:
              - name: code
                class: code
      config:
        default_handler: python
        python:
          use_indentation: '\t'
  - glightbox
  - search
  - awesome-pages
  - git-revision-date-localized
  # - print-site:
  #     add_to_navigation: true


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  # Extensions for notes, warnings, ...
  # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#fontawesome
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

nav:
  - Introduction: index.md

  - Installation: topics/admin/install.md


  - Tutorials:
    - Hello World: tutorials/01_hello_world.md
    - Creating a web server: tutorials/02_web_server.md
    - Creating a microservice with REST API: tutorials/03_rest_api.md

    # - Services:
    #   # - topics/asab/web/index.md
    #   # - topics/asab/web/auth.md
    #   # - topics/asab/web/cors.md
    #   # - topics/asab/web/restapidocs.md
    #   # - topics/asab/library.md

  - Topics:
    # - topics/asab/application.md
    # - topics/asab/config.md
    # - topics/asab/log.md
    # - topics/asab/metrics.md
    # - topics/asab/module.md
    # - topics/asab/pubsub.md
    # - topics/asab/service.md
    - Storage:
      - Intro: topics/asab/storage/intro.md
      - Manipulation with Databases: topics/asab/storage/manipulation_with_databases.md
      - Encryption and Decryption: topics/asab/storage/encryption.md
      - In-Memory Storage: topics/asab/storage/inmemory.md
      - MongoDB Storage: topics/asab/storage/mongodb.md
      - ElasticSearch Storage: topics/asab/storage/elasticsearch.md
    # - topics/asab/various.md
    # - topics/asab/zookeeper.md

  - Reference:
    # - reference/application.md
    # - reference/config.md
    # - reference/library.md
    # - reference/log.md
    # - reference/metrics.md
    # - reference/module.md
    - Storage:
        - StorageService: reference/storage/service.md
        - Upsertor: reference/storage/upsertor.md
        - Exceptions: reference/storage/exceptions.md
        - ElasticSearch: reference/storage/elasticsearch.md
        - MongoDB: reference/storage/mongodb.md
        - In-Memory: reference/storage/inmemory.md

  - Administration:
    - topics/admin/command-line.md
    - topics/admin/containers.md
    - topics/admin/systemd.md

  - topics/asab/alert.md