site_name: ASAB
repo_url: https://github.com/TeskaLabs/asab
repo_name: TeskaLabs/asab

# THEME, COLORS, FONTS, ICONS

theme:
  name: "material"
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate #
    - navigation.tabs
    - navigation.footer
    - navigation.indexes
    - navigation.top  # back-to-the-top button when scrolling up
    - navigation.tracking
    - attr_list
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - def_list
    - search.suggest  # autocomplete the search query
    - search.share  # share the queried endpoint

  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      failure: fontawesome/solid/xmark
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
    
    repo: fontawesome/brands/github

  font:
    text: Verdana

  palette:
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: yellow
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


# PLUGINS

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            # https://mkdocstrings.github.io/python/usage/configuration/docstrings/
            docstring_style: google  # | google | numpy | sphinx
            docstring_section_style: table  # table | list | spacy
            show_if_no_docstring: true
            show_docstring_description: false
  - glightbox
  - search
  - awesome-pages
  - git-revision-date-localized
  - tags
  - autorefs  # https://mkdocstrings.github.io/usage/#cross-references-to-any-markdown-heading


markdown_extensions:
  # Syntax highlighting
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables

  # Admonitions (call-outs) https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - admonition
  - pymdownx.details
  - pymdownx.superfences  # arbitrary nesting of code and tabs

  # Annotations https://squidfunk.github.io/mkdocs-material/reference/annotations/
  - attr_list
  - md_in_html

  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

  # Content tabs and anchor links https://squidfunk.github.io/mkdocs-material/reference/content-tabs/
  - pymdownx.tabbed:
      alternate_style: true

extra:
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/TeskaLabs/asab

# NAVIGATION TREE

nav:
  - Home: index.md

  - Getting started:
    - Installation and first application: getting-started/installation_first_app.md
    - Creating a web server: getting-started/web_server.md
    - Containerization: getting-started/containers.md

  - How-To Guides:
    - Creating a microservice with REST API: how-tos/03_rest_api.md

  - Topics:
    # - topics/asab/application.md
    # - topics/asab/config.md
    # - topics/asab/log.md
    # - topics/asab/metrics.md
    # - topics/asab/module.md
    # - topics/asab/pubsub.md
    # - topics/asab/service.md
    - Storage:
      - Introduction: topics/asab/storage/intro.md
      - Manipulation with Databases: topics/asab/storage/manipulation_with_databases.md
      - Encryption and Decryption: topics/asab/storage/encryption.md
      - In-Memory Storage: topics/asab/storage/inmemory.md
      - MongoDB Storage: topics/asab/storage/mongodb.md
      - ElasticSearch Storage: topics/asab/storage/elasticsearch.md
    - Metrics:
      - Introduction: topics/asab/metrics/intro.md
      - Tags: topics/asab/metrics/tags.md
      - Built-in metrics: topics/asab/metrics/built-ins.md
      - Monitoring: topics/asab/metrics/targets.md
    # - topics/asab/various.md
    # - topics/asab/zookeeper.md

  - Reference:
    # - reference/application.md
    # - reference/config.md
    # - reference/library.md
    # - reference/log.md
    - Metrics:
      - MetricsService: reference/metrics/service.md
      - Gauge: reference/metrics/gauge.md
      - Counter: reference/metrics/counter.md
      - EPSCounter: reference/metrics/eps_counter.md
      - DutyCycle: reference/metrics/duty_cycle.md
      - AggregationCounter: reference/metrics/aggregation_counter.md
      - Histogram: reference/metrics/histogram.md
      - CounterWithDynamicTags: reference/metrics/counter_with_dynamic_tags.md
      - AggregationCounterWithDynamicTags: reference/metrics/aggregation_counter_with_dynamic_tags.md
      - HistogramWithDynamicTags: reference/metrics/histogram_with_dynamic_tags.md
    # - reference/module.md
    - Storage:
        - StorageService: reference/storage/service.md
        - Upsertor: reference/storage/upsertor.md
        - Exceptions: reference/storage/exceptions.md
        - ElasticSearch: reference/storage/elasticsearch.md
        - MongoDB: reference/storage/mongodb.md
        - In-Memory: reference/storage/inmemory.md
  
  - Contributing: contributing.md

  # Examples are rendered automatically with create_examples.py script
  - Examples:
    - examples/hello_world.py
    - examples/config_geturl.py
    - examples/storage_mongodb.py
    - examples/websocket-chat.py
    - examples/metrics-web-requests.py
    - examples/argparser.py
    - examples/task.py
    - examples/data
    - examples/json_schema.py
    - examples/config_getseconds.py
    - examples/.mypy_cache
    - examples/library-subscribe.py
    - examples/storage_inmemory.py
    - examples/webserver.py
    - examples/ssl
    - examples/zookeeper.py
    - examples/application_states.py
    - examples/webapp
    - examples/library.py
    - examples/service-discovery.py
    - examples/executor.py
    - examples/metrics.py
    - examples/timer.py
    - examples/pubsub.py
    - examples/zookeeper-advertise.py
    - examples/web-authz-userinfo.conf
    - examples/storage_elasticsearch.py
    - examples/logging-file.py
    - examples/web-authz-rbac.py
    - examples/pdict.py
    - examples/websocket-chat.html
    - examples/library-git-provider.py
    - examples/web-authz-userinfo.py
    - examples/web-auth.py
